### ISSUE TITLE
Popup menu also in settings

### ISSUE THREAD

**Issue by S1M0N38** [henices/Chrome-proxy-helper#14]
I think it would be nice to include the popup menu

![screen shot 2018-06-07 at 12 27 55](https://user-images.githubusercontent.com/22257750/41161406-1e8636d8-6b33-11e8-95fd-e0e6aaa9f717.png)

in settings page

![screen shot 2018-06-07 at 12 35 20](https://user-images.githubusercontent.com/22257750/41161426-284134ca-6b33-11e8-9c98-b042649c7d55.png)

so It 's easier to use your extension with an automated script (like selenium).

**Comment by Tosin33** [comment]
I need help, the new version does not have the full option from which to select from 
![Uploading IMG-20210723-WA0007.jpeg…]()
