### ISSUE TITLE
PAC File URL Support

### ISSUE THREAD

**Issue by rtfmoz2** [henices/Chrome-proxy-helper#25]
There is no way to access the current company PAC file without the url option. This eliminates the use of the extension as a valid option. Slightly bad timing because yesterday I recommended this extension to 5k developers and the next day, key functionality is removed.

**Comment by henices** [comment]
Ok， I will bring back

**Comment by henices** [comment]
@rtfmoz2 new version of chrome proxy helper is release on Google web store, sorry for this inconvenience.

**Comment by rtfmoz2** [comment]
Thank you! Using it now!
