### ISSUE TITLE
why was Blacklist support removed?

### ISSUE THREAD

**Issue by pepijnmm** [henices/Chrome-proxy-helper#36]
I saw that in commit https://github.com/henices/Chrome-proxy-helper/commit/ccf3a2f712a6ebac4c866b59fbc8e5281a111b0c
Blacklist started to be removed as an option. and with some commits after that, it got fully hidden as an option with only whitelist remaining.
But I can't find any issue/pr on the reason why. I wanted to use this extension to only enable the proxy on certain websites. So this option would be usefull for me.  
Is there a technical reason to not use it?

**Comment by Bonjour123** [comment]
Any update ?

**Comment by pepijnmm** [comment]
@Bonjour123 As far as I could tell it's because chrome.proxy is now used and that only has a bypass list option.
https://developer.chrome.com/docs/extensions/reference/proxy/
Bypass list: "Individual servers may be excluded from being proxied with the bypassList"
It's not regex sadly.

**Comment by henices** [comment]
> @Bonjour123 As far as I could tell it's because chrome.proxy is now used and that only has a bypass list option. https://developer.chrome.com/docs/extensions/reference/proxy/ Bypass list: "Individual servers may be excluded from being proxied with the bypassList" It's not regex sadly.

pac script can set proxy only for some domains.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file

**Comment by henices** [comment]
> I saw that in commit [ccf3a2f](https://github.com/henices/Chrome-proxy-helper/commit/ccf3a2f712a6ebac4c866b59fbc8e5281a111b0c) Blacklist started to be removed as an option. and with some commits after that, it got fully hidden as an option with only whitelist remaining. But I can't find any issue/pr on the reason why. I wanted to use this extension to only enable the proxy on certain websites. So this option would be usefull for me. Is there a technical reason to not use it?

The blacklist UI is a mistake. I did not write any code for the blacklist feature. Ten years ago, all Chrome proxy extensions had bugs, so I wrote my own. I may add Manifest V3 support for this extension in the future.

**Comment by pepijnmm** [comment]
Thx henices, I will take a look if I have time soon to see if I I can generate the pac file on the fly to generate the blacklist. 
Seems to be possible: https://stackoverflow.com/questions/9022322/using-a-local-proxy-auto-configuration-pac-file-for-proxy-settings-from-a-chr

@henices I already have manifest 3 running on my fork. But I changed how it starts a proxy by moving more stuff to the background jsso it won't be a copy paste.

**Comment by henices** [comment]
We can use pac to set domain blacklist, here is an exmaple:

https://github.com/henices/Chrome-proxy-helper/blob/master/example.pac
