### ISSUE TITLE
include option (only enable proxy on these sites)

### ISSUE THREAD

**Issue by nwgat** [henices/Chrome-proxy-helper#5]
would been nice if there was a include list, so that people can configure to enable proxy on google.com but not on google.co.uk etc

aka "enable on google.com, disable on everywhere else list"

**Comment by henices** [comment]
Thank you for suggestion

**Comment by ramytamer** [comment]
Is there any one working on this feature ? If not I can start working on it.

**Comment by WeslyG** [comment]
@ramytamer I want release this release this function too. let's start!

**Comment by henices** [comment]
Ok, Let's start !

**Comment by AndreaLeidi** [comment]
hi, after the last update 1.3.2 - 11.26.2020 automatically performed by the browser I can only set a sites whitelist, the blacklist mode is missing in the "Rules mode" dropdown menu. Furthermore, as a result of this modification, my pre-existing blacklist was lost.

**Comment by henices** [comment]
@

> hi, after the last update 1.3.2 - 11.26.2020 automatically performed by the browser I can only set a sites whitelist, the blacklist mode is missing in the "Rules mode" dropdown menu. Furthermore, as a result of this modification, my pre-existing blacklist was lost.

@AndreaLeidi  Sorry for this inconvenience. I'm so busy these years, through the blacklist mode was in the option page, it hasn't been implemented yet.  Perhaps I would be able to write some javascript code for it in some days.

**Comment by Mehoff** [comment]
Glad you are still working on this extension! Wish you luck with blacklist implementation - this is really handy feature!

**Comment by henices** [comment]
Now extension support local custom pac script. close this issue.
